# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://UMiamiASME.github.io
title: UMiami ASME
email: hurricane.asme@gmail.com
author: UMiamiASME
description: > # "Write an awesome description for your new site here. 
  Welcome to the official website for the American Society of Mechanical Engineers (ASME) at the University of Miami!
copyright: 'Copyright &copy; 2017 UMiami ASME. All Rights Reserved.'
credits: 'Credits: open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Facebook
    url: https://www.facebook.com/UMASME/
    icon: facebook-square 
  - title: OrgSync
    url: https://orgsync.com/55150/chapter/
    icon: orgsync
  - title: github
    url: https://github.com/UMiamiASME/
    icon: github
