# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://UMiamiASME.github.io
title: University of Miami ASME
email: hurricane.asme@gmail.com
author: UMiamiASME
description: > 
  Welcome to the official website for the American Society of Mechanical Engineers (ASME) at the University of Miami!
copyright: 'Copyright &copy; 2017 UMiami ASME. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Facebook
    url: https://www.facebook.com/UMASME/
    icon: facebook-square 
  - title: OrgSync
    url: https://orgsync.com/55150/chapter/
    icon: undo 
  - title: Email
    url: mailto:hurrican.asme@gmail.com
    icon: envelope
